version: "3"

networks:
  postgresnet-sacsis:
  flasknet-sacsis:

services:
  postgresql-sacsis:
    container_name: postgresql-sacsis
    restart: always
    image: postgres:9.6
    hostname: postgresql-sacsis
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sacsisdb
    networks:
      - postgresnet-sacsis
    volumes:
      - postgres-sacsis-data:/var/lib/postgresql/data

  pgweb-sacsis:
    container_name: pgweb-sacsis
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "5050:8081"
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgresql-sacsis/sacsisdb?sslmode=disable
    depends_on:
      - postgresql-sacsis
    networks:
      - postgresnet-sacsis

  flask-sacsis:
    container_name: api-sacsis
    restart: always
    build: ./api
    hostname: flask-sacsis
    environment:
      - MASTER_ADM_LOGIN=admin@admin.br
      - MASTER_ADM_PASSWORD=admin
      - JWT_KEY=The quick brown fox jumps over the lazy dog
      - DATABASE_URL=postgresql://admin:admin@postgresql-sacsis/sacsisdb
      - TZ=Brazil/East
    volumes: 
      - ./api:/aplication
    depends_on:
      - postgresql-sacsis
    ports:
      - "5000:5000"
    networks:
      - postgresnet-sacsis
      - flasknet-sacsis

  nginx-sacsis:
    container_name: nginx-sacsis
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sacsis.tech:/etc/nginx/sites-available/sacsis.tech
      - ./app.sacsis.tech:/etc/nginx/sites-available/app.sacsis.tech
    depends_on:
      - flask-sacsis
    networks:
      - flasknet-sacsis


volumes:
  postgres-sacsis-data: